### ISSUE TITLE
Valid check, 11A2F26 namespace

### ISSUE THREAD

**Issue by AbuBaniaz** [LraiZer/AutoBouquets#10]
Several services are using the `11A2F26` namespace. Can we use both `11A000` & `11A2F26` for the valid check, or maybe even if namespace starts with `11A`?  Sky News and Pick+1 are two examples to test with. 

https://github.com/LraiZer/AutoBouquets/blob/master/autobouquets_e2.sh#L235:L240

**Comment by LraiZer** [comment]
I will look to see, also valid service is checked for 11A0000 in plugin.py for users not using the script on a cronjob.

**Comment by AbuBaniaz** [comment]
We might need to take this into account

https://github.com/oe-alliance/AutoBouquetsMaker/commit/75bc959123dac68dff7094d0d0340c5014333b76

Scan.cpp also amended

**Comment by LraiZer** [comment]
So that you are able to make any OpenViX users of AB aware if they encounter this...

Following this commit: https://github.com/OpenViX/enigma2/commit/60c8c2b30d30bb98d5a6eb1ad47c5c55b57be927 currently means this transponder will no longer match namespace in the bouquets with lamedb when generated by an engima2 service scan initiated by AB when the 'Use Internal NIT Scan' option is turned off in the AB plugin. The bouquets are still created from BAT in AB and continue have 11A2F26 but the lamedb would have 11A0000 as it was created from an engima2 service scan.

I can't get rid of 11A2F26 when 'Use NIT scan' is disabled in AB for this transponder as for every other distro, their engima2 service scan does not have this commit and still uses 11A2F26 . If the default option of using NIT scan is not changed and is still enabled, then there is no problem as both lamedb and bouquets will still both have 11A2F26, it is only when NIT is turned off in AB on OpenViX now, that different namespaces would be created.

I very much doubt anyone uses AB with NIT scan turned off, or actually uses AB at all now most use ABM.. so probably just a minor issue for one in a million users.

**Comment by AbuBaniaz** [comment]
OK, noted. PLI and ATV have the commit too.

**Comment by LraiZer** [comment]
If the majority of the more popular distros now have this change, it will need to be reflected in AB and also should prompt other distros to also apply this change. I will look to see what is needed.
