### ISSUE TITLE
Red button section number changes

### ISSUE THREAD

**Issue by AbuBaniaz** [LraiZer/AutoBouquets#14]
BBC red button section has changed numbers.  I can't get to the build machine to test building a modified reader.

https://www.sky.com/tv-guide/20230509/4101-1/970/
https://github.com/LraiZer/AutoBouquets/blob/master/autobouquetsreader.cpp#L880:L881

**Comment by LraiZer** [comment]
I will look at it when i get chance to fire up my buildbox.

They will have moved the red button 10 channels back now there is more room in regional in preparation for the extra Wimbledon red button channels i guess.

Change:
http://commando.org.uk/wiki/bskyb/updates/2023/04/wiki-updates-2023-04-12-0600.html

Current:
http://commando.org.uk/wiki/bskyb/4101-255.html

All the custom_sort_X.txt files will also need their RB bouquet range moving down and changing from 19 to 20.
https://github.com/LraiZer/AutoBouquets/blob/master/custom_sort_1.txt#L944-L956

**Comment by AbuBaniaz** [comment]
>All the custom_sort_X.txt files will also need their RB bouquet range moving down and changing from 19 to 20.

Why would we need to change from 19 to 20? Surely only the boundaries are changing and not the number of ranges?
i.e 19 now ends at 969 and 20 starts at 970?

Anyway, good thing we created  a branch for testing even though we have not used properly.

**Comment by LraiZer** [comment]
There is also currently an issue with a rogue ITV1+1 at position 973 that may have to move to "other" bouquet using its channel_id as ref to change its pos to 0xffff in supplement.txt

**Comment by AbuBaniaz** [comment]
I vaguely remember a post on using Hexeditor to edit the reader.  Alas, ukcvs is not available.

**Comment by LraiZer** [comment]
Initial commit was deliberately coded so that it was hex editor hackable to be able to change certain service channel_id ranges without the need to recompile. But that was changed in this commit in autobouquetsreader.cpp.
https://github.com/LraiZer/AutoBouquets/commit/6e4b911009ebb7d561475ff14fd78553141a8f63#diff-2564426058d29ba78ec3ab3d4d23e07fc4005bbbc529bdd36999cbb02d815b01L766-L774

We used to convert strings to numbers in the binary so we could hack them ;)

not much in there still hex hackable if you look:
strings /usr/lib/enigma2/python/Plugins/Extensions/AutoBouquets/autobouquetsreader

**Comment by AbuBaniaz** [comment]
I have made the changes here. https://github.com/LraiZer/AutoBouquets/commit/a45e1a8727cd9d37ede9aa161ecdc5cdc9fbbe49
We can pick the commit and then delete the branch later.

**Comment by AbuBaniaz** [comment]
Also, what would you like to do about references to `www.ukcvs.net`?

**Comment by LraiZer** [comment]
changes look exactly as i was going to change, you can run with that to close the issue.

we can keep www.ukcvs.net for posterity, sources are on github now and image teams bitbakes point here. we are easy to find here.
