### ISSUE TITLE
Sort "Other" section alphabetically

### ISSUE THREAD

**Issue by AbuBaniaz** [LraiZer/AutoBouquets#9]
Is it possible to sort the "Other" section alphabetically. Similar to this but numbers first?

https://github.com/oe-alliance/AutoBouquetsMaker/commit/88a07dd1acded065f403d1d5e7fd9d6a29c04fdb

Thanks in advance

**Comment by LraiZer** [comment]
We should keep current sorting order in Other bouquet as it has multiple sections by design with separator markers and as it is written by more than one code loop and as such is not really easily sorted as a whole single bouquet.

The numbers before the channel names have different meanings in the Other bouquet depending on which section they are in. We first have the range 951 - 999 as standard, then we have the -- Extra Channels -- which are unused allocated channels outside of the 951 - 999 range in position order, and finally we have -- Extra Services-- which are unallocated channel positions and show their channel epgid number instead of their 65535 (0xffff) channel number along side them and are sorted into epgid order.

The current ordering seems more logical than alpha sorted with numbers with different meanings all jumbled up.
